### ISSUE TITLE
[RFE] extend task specification with target providers

### ISSUE THREAD

**Issue by ingvagabund** [gofed/ichiba#1]
Not every task is meant to be run via every provider. E.g.

``` yaml
name: provision-cluster
description: Provision a cluster with VMs
providers: ["jenkins", "vagrant"]
```
